<?php

/**
 * @file
 * Contains sample_master_control.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sample_master_control_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sample_master_control':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Sample Master Control module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function sample_master_control_mail($key, &$message, $params) {
  switch ($key) {
    case 'sample_email':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}